import org.code.neighborhood.*;

public class MinionPainter extends MuralPainter {


public void paintMinion (String bodyColor, String overallColor, String shoeColor, String goggleColor, String eyeColor, String pupilColor, String irisColor, String secondIrisColor) {
  getToStartBody();
  paintBody(bodyColor);
  getToStartOverall();
  paintOverall(overallColor);
  paintShoes(shoeColor);
  getToStartGoggles();
  paintGoggles(goggleColor);
  paintEyes(eyeColor);
  paintPupil(pupilColor);
  paintIris(irisColor,secondIrisColor);
  paintArms(bodyColor);
  paintGloves(shoeColor);
  paintSmile(shoeColor);
}

public void getToStartBody(){
  turnRight();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();

  turnLeft();

  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
  move();
}
  
  public void paintBody(String color){
    paintLine (color,8);
    turnRight();
    move();
    turnRight();
    paintLine (color,10);
    turnLeft();
    move();
    turnLeft();
    paintLine (color,12);
    turnRight();
    move();
    turnRight();
    paintLine (color,14);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine (color,14);
    turnRight();
    move();
    turnRight();
    move();
    paintLine (color,14);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine (color,14);
    turnRight();
    move();
    turnRight();
    move();
    paintLine (color,14);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine (color,14);
    turnRight();
    move();
    turnRight();
    move();
    paintLine (color,14);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine (color,14);
  }

  public void getToStartOverall(){
    turnRight();
    move();
    turnRight();
    move();    
  }

  public void paintOverall(String color){
    paintLine (color,14);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine (color,14);
    turnRight();
    move();
    turnRight();
    move();
    paintLine (color,14);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine (color,14);
    turnRight();
    move();
    turnRight();
    move();
    move();
    move();
    paintLine (color,10);
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine (color,3);
    move();
    move();
    move();
    move();
    paintLine (color,3);
  }
  public void paintShoes(String color){
    turnLeft();
    turnLeft();
    move();
    turnLeft();
    turnLeft();
    paintLine (color,1);
    turnRight();
    paintLine (color,2);
    turnRight();
    paintLine(color,4);
    move();
    move();
    move();
    move();
    paintLine(color,3);
    turnRight();
    paintLine (color,1);
    turnRight();
    paintLine (color,2);
    
  }
  public void getToStartGoggles(){
    turnLeft();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    turnLeft();
    move();
    move();
    move();
    turnRight();
  }
  public void paintGoggles(String color){
    paintLine(color,4);
    turnRight();
    paintLine(color,2);
    turnAround();
    move();
    turnRight();
    move();
    turnRight();
    paintLine(color,5);
    move();
    paintLine(color,5);
    turnRight();
    move();
    paintLine(color,5);
    turnRight();
    move();
    paintLine(color,5);
    move();
    paintLine(color,5);
    turnAround();
    move();
    move();
    move();
    move();
    move();
    move();
    turnLeft();
    move();
    paintLine(color,5);
    turnRight();
    move();
    turnRight();
    move();
    paint(color);
    move();
    move();
    move();
    move();
    paint(color);
    turnLeft();
    move();
    move();
    move();
    move();
    paint(color);
    turnLeft();
    move();
    move();
    move();
    move();
    paint(color);
    turnLeft();
    move();
    move();
    move();
    move();
    move();
    move();
    paint(color);
    turnLeft();
    move();
    move();
    move();
    move();
    paint(color);
    turnRight();
    move();
    move();
    move();
    move();
    paint(color);
    turnAround();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    turnLeft();
    move();
    paintLine(color,3);    
  }
  public void paintEyes(String color){
    turnLeft();
    move();
    move();
    move();
    paintLine(color,3);    
    turnLeft();
    move();
    turnLeft();
    paintLine(color,5);    
    turnRight();
    move();
    turnRight();
    move();
    paintLine(color,5);    
    turnLeft();
    move();
    turnLeft();
    move();
    paintLine(color,5);
    turnRight();
    move();
    turnRight();
    move();
    move();
    paintLine(color,3);
    move();
    move();
    move();
    paintLine(color,3);
    turnRight();
    move();
    turnRight();
    paintLine(color,5);
     turnLeft();
    move();
    turnLeft();
    move();
    paintLine(color,5);
    turnRight();
    move();
    turnRight();
    move();
    paintLine(color,5);
    turnLeft();
    move();
    turnLeft();
    move();
    move();
    paintLine(color,3);  
  }
    public void paintPupil(String color){
    turnLeft();
    move();
    turnLeft();
    move();
    paint(color);
    move();
    move();
    move();
    move();
    move();
    move();
    paint(color);    
    }
  public void paintIris(String color, String secondColor){
    move();
    paint(color);    
    turnRight();
    move();
    paint(color);    
    turnRight();
    move();
    paint(color);    
    move();
    move();
    move();
    move();
    move();
    move();
    turnAround();
    paint(secondColor);    
    move();
    paint(secondColor);    
    turnLeft();
    move();
    paint(secondColor);    
  }
  public void paintArms(String color){
    turnAround();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    turnRight();
    move();
    move();
    move();
    move();
    paintLine(color,4);    
    turnAround();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    paintLine(color,4);    
  }

  public void paintGloves(String color){
    paintLine(color,2);
    turnRight();
    move();
    turnRight();
    move();
    move();
    move();
    turnRight();
    paintLine(color,3);
    turnLeft();
     move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    turnLeft();
    move();
    move();
    turnRight();
    paintLine(color,2);
    turnRight();
    move();
    turnRight();
    move();
    move();
    move();
    turnRight();
    paintLine(color,3);
  }
    public void paintSmile(String color){
      turnLeft();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    move();
    turnLeft();
    move();
    move();
    move();
   turnRight();
    paintLine(color,4);
    
      
    }
}